name: Deploy
on:
    push:
        branches: [master]
jobs:
    Compile:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn
            - run: npx webpack
