name: Deploy
on:
    push:
        branches: [master]
jobs:
    Compile:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: compile
              run: |
                  yarn
                  npx webpack
            - name: archive artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: public-folder
                  path: |
                      public
